#!/bin/bash

set -e

IFS= read -r -s -p "Enter lioadmin password for GRUB: " ADMIN_PASS
# printf "'%s'\n" "${ADMIN_PASS}"
echo
IFS= read -r -s -p "Repeat: " ADMIN_PASS_REPEAT
# printf "'%s'\n" "${ADMIN_PASS_REPEAT}"
echo

if [ "${ADMIN_PASS}" != "${ADMIN_PASS_REPEAT}" ]; then
    echo "ERROR: Passwords don't match."
    exit 1
fi

GRUB_PWD_HASH=$(printf "%s\n%s" "${ADMIN_PASS}" "${ADMIN_PASS}" | grub-mkpasswd-pbkdf2 | awk '/grub.pbkdf/{print$NF}')
mkdir -p config/includes.chroot/boot/grub
cat > config/includes.chroot/boot/grub/custom.cfg <<EOF
set superusers="lioadmin"
password_pbkdf2 lioadmin ${GRUB_PWD_HASH}
EOF

PRESEED=config/includes.binary/preseed/auto.cfg
cat >> ${PRESEED} <<EOF
d-i preseed/late_command string in-target /usr/share/liox-config/d-i_hooks
EOF

echo -n "Enter lioadmin user "
ADM_PWD_HASH=$(printf "%s\n" "${ADMIN_PASS}" | mkpasswd -m sha-512 | sed -e 's/\//\\\//g')
sed -i -e '/^d-i passwd\/username/ s/user$/lioadmin/' ${PRESEED}
sed -i -e '/^d-i passwd\/user-password/ s/^d-i/#d-i/' ${PRESEED}
sed -i -e "/^#d-i passwd\\/user-password-crypted/ { s/^#d-i/d-i/; s/\\[.*$/${ADM_PWD_HASH}/ }" ${PRESEED}
