#!/bin/sh

set -e

case "$LIOX_ARCH" in
    i386)
        LX_ARCHS=i386
        LX_FLAVS=686-pae
        ;;
    amd64)
        LX_ARCHS=amd64
        LX_FLAVS=amd64
        ;;
    *)
        echo "Please specify LIOX_ARCH (i386 or amd64)"
        exit 1
        ;;
esac

# '--debian-installer-distribution daily' is a workaround to make d-i kernel and
# live image modules match.
lb config noauto \
    --architectures $LX_ARCHS \
    --linux-flavours $LX_FLAVS \
    --distribution buster \
    --archive-areas "main contrib non-free" \
    --debootstrap-options "--include=apt-transport-https,ca-certificates,openssl" \
    --debian-installer live \
    --debian-installer-distribution daily \
    --hdd-size 7600 \
    --security true \
    --updates true \
    "${@}"

cp -rT config_overlay config

# This is required because Visual Studio Code doesn't have a 32-bit repo at the
# moment, so we need to have a way to diverge configurations between i386/amd64.
if [ "${LIOX_ARCH}" = "amd64" ]; then
    cp -rT config_overlay_amd64 config
fi

if [ -n "${LIOX_CONTEST}" ]; then
    cp -rT config_overlay_contest config
    ./contest-config
fi
