#!/bin/sh
set -e

case "${1}" in
	prereqs)
		echo ""
		exit 0
		;;
esac

. /usr/share/initramfs-tools/hook-functions
copy_exec /sbin/kpartx /sbin/
copy_exec /usr/bin/wget /usr/bin/
copy_exec /usr/bin/xz /usr/bin/

exit 0
