#!/bin/bash

set -e

for P in $(ls /usr/share/liox-config/patches/*.patch); do
    patch -d/ -p0 < ${P}
done

cp -aT /usr/share/liox-config/post-inst-overlay /

systemctl disable apt-daily-upgrade.timer
systemctl disable apt-daily.timer
update-grub
