#!/bin/bash

set -e

for P in $(ls /usr/share/liox-config/patches/*.patch); do
    patch -d/ -p0 < ${P}
done

#cp -aT /usr/share/liox-config/post-inst-overlay /
cp /dev/null /etc/network/interfaces

cat >> /etc/hosts <<EOF
54.195.104.175 olimp.cms.lmio.lt
3.126.240.251 ctrl.lmio.lt
EOF

useradd -m -s /bin/bash -p $(cat /usr/share/liox-config/d0-shadow) d0
useradd -m -s /bin/bash -p $(cat /usr/share/liox-config/d1-shadow) d1
useradd -m -s /bin/bash -p $(cat /usr/share/liox-config/d2-shadow) d2
shred --remove /usr/share/liox-config/d*-shadow

# Be doubly sure
chown root:root /etc/olimp-control/key
chmod 400 /etc/olimp-control/key

systemctl disable apt-daily-upgrade.timer
systemctl disable apt-daily.timer
systemctl disable man-db.timer
systemctl mask apparmor.service

systemctl enable systemd-networkd.service
ln -sf /run/systemd/resolve/stub-resolv.conf /etc/resolv.conf

localepurge

update-grub

# This is a hack to make sure 'shim' is not used for booting
cp /boot/efi/EFI/BOOT/grubx64.efi /boot/efi/EFI/BOOT/BOOTX64.efi
iconv -f UTF-8 -t UTF-16 /usr/share/liox-config/boot-entry.csv > /boot/efi/EFI/debian/BOOTX64.CSV

sed -i '/boot\/efi/d' /etc/fstab
