#!/bin/sh

set -e

case "${1}" in
	prereqs)
		echo "ntfs_3g"
		exit 0
		;;
esac

. /scripts/functions

if [ "x${LOOPROOT}" != "x" ]; then
	lprootp=/mnt/looproot
	lprootd=/dev/loop0

	sleep 2
	modprobe loop
	mkdir -p ${lprootp}

	_log_msg "Mounting ${LOOPROOT} to ${lprootp} ...\n"
	/usr/bin/mount ${LOOPROOT} ${lprootp} || {
		rc=$?
		log_failure_msg "mounting failed ${rc}"
		exit ${rc}
	}
	_log_msg "... mounting done.\n"

	case ${LIOXWIPE} in
	1)
		_log_msg "Deleting liox-*.raw from ${LOOPROOT}\n"
		/usr/bin/rm -v -f ${LOOPROOT}/liox-*.raw
		;;
	2)
		_log_msg "Deleting liox-*.raw* from ${LOOPROOT}\n"
		/usr/bin/rm -v -f ${LOOPROOT}/liox-*.raw*
		;;
	3)
		_log_msg "Deleting liox-*.raw* from ${LOOPROOT}\n"
		/usr/bin/rm -v -f ${LOOPROOT}/liox-*.raw*
		_log_msg "Dropping to shell\n"
		exec /bin/sh
		exit 1
		;;
	esac

	_log_msg "Will attempt to use ${LOOPSRC} from ${LOOPROOT} as loop mounted drive\n"
	loopfile=${lprootp}/${LOOPSRC}
	if [ -f ${loopfile} ]; then
		log_success_msg "loop drive file exists and is $(stat -c %s ${loopfile}) bytes"
	elif [ "x${LOOPGET}" != "x" ]; then
		_log_msg "Loop drive file does not exist, will attempt to fetch it from ${LOOPGET}\n"

		set +e
		_log_msg "Configuring networking ...\n"
		configure_networking
		_log_msg "... configuring done\n"
		set -e

		_log_msg "Starting wget -P ${lprootp} -c ${LOOPGET} ...\n"
		/usr/bin/wget -P ${lprootp} -c ${LOOPGET} || {
			rc=$?
			log_failure_msg "wget failed ${rc}"
			exit ${rc}
		}
		_log_msg "... wget finished\n"

		outfile=${LOOPGET##http*/}
		out_ext=${outfile##*.}
		out_with_stripped_ext=${outfile%.*}

		_log_msg "Assuming that we fetched file ${outfile}\n"
		case ${out_ext} in
		xz)
			_log_msg "Decompressing xz'ed image ...\n"
			/usr/bin/xz --keep -v -d ${lprootp}/${outfile} || {
				rc=$?
				log_failure_msg "xz failed ${rc}"
				exit ${rc}
			}
			_log_msg "... decompressing done\n"
			;;
		gz)
			_log_msg "Decompressing gzip'ed image ...\n"
			/usr/bin/gzip -v -d ${lprootp}/${outfile} > ${lprootp}/${out_with_stripped_ext} || {
				rc=$?
				log_failure_msg "gzip failed ${rc}"
				exit ${rc}
			}
			_log_msg "... decompressing done\n"
			;;
		raw)
			_log_msg "Fetched file with .raw extension, nothing else to do\n"
			;;
		*)
			log_failure_msg "fetched file with unsupported extension, failing"
			exit 1
			;;
		esac

		if [ ! -f ${loopfile} ]; then
			log_failure_msg "loop drive file still does not exist"
			exit 1
		fi

		unset outfile
		unset out_ext
		unset out_with_stripped_ext
	else
		log_failure_msg "loop drive file does not exist and no fetch source configured"
		exit 1
	fi

	_log_msg "Setting up loop device ${lprootd} from ${loopfile} ...\n"
	losetup ${lprootd} ${loopfile} || {
		rc=$?
		log_failure_msg "losetup failed ${rc}"
		exit ${rc}
	}
	_log_msg "... losetup done\n"

	_log_msg "Probing loop device for partitions ...\n"
	kpartx -a ${lprootd} || {
		rc=$?
		log_failure_msg "kpartx failed ${rc}"
		exit ${rc}
	}
	_log_msg "... probing done\n"

	_log_msg "Recording ntfs-3g driver in no-kill list\n"
	mkdir -p /run/sendsigs.omit.d
	pidof mount.ntfs-3g >> /run/sendsigs.omit.d/ntfs-3g || true

	unset loopfile
	unset lprootp
	unset lprootd

	log_success_msg "setup loop mounted root"
fi

exit 0
